services:
  backend:
    image: pratham246/grocery-backend:latest
    container_name: grocery-backend
    ports:
      - 5513:5513
    networks:
      - backendNetwork
    env_file:
      - .env
    restart: always

networks:
  backendNetwork:
    driver: bridge