# name: Deploy to EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Docker
#       uses: docker/setup-buildx-action@v1

#     - name: Build and push Docker image
#       run: |
#         docker build -t your-dockerhub-username/your-image-name:latest .
#         echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
#         docker push your-dockerhub-username/your-image-name:latest

#     - name: SSH and deploy
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.EC2_HOST }}
#         username: ${{ secrets.EC2_USER }}
#         key: ${{ secrets.EC2_KEY }}
#         script: |
#           cd /path/to/your/project
#           git pull origin main
#           docker-compose down
#           docker-compose up -d --build